import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Autocomplete, TextField, Typography, Grid } from "@mui/material";
import styles from "../styles/Home.module.css";
import { UserCompact } from "../shared/types";

const Home: NextPage = () => {
  const [selectedUser, setSelectedUser] = useState<UserCompact | null>(null);
  const [options, setOptions] = useState<Array<UserCompact>>([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>GitHub user mega searcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h2" className={styles.title}>
          Search for a GitHub user:
        </Typography>

        <Autocomplete
          id="github-username-autocomplete"
          autoHighlight
          filterOptions={(x) => x}
          options={options}
          sx={{ width: 300 }}
          renderInput={(params) => <TextField {...params} label="Username" />}
          getOptionLabel={(option: UserCompact) => option.name}
          onChange={(_, newValue) => {
            setSelectedUser(newValue);
          }}
          onInputChange={async (_, newInputValue) => {
            if (newInputValue.length > 1) {
              // Only search the API if we have a query string of length > 1
              const fetchRes = await fetch(`/api/search?q=${newInputValue}`);
              const data = await fetchRes.json();

              // Populate the dropdown with the results
              setOptions(data.users);
            }
          }}
          renderOption={(props, option) => {
            const { name, img_url } = option;
            return (
              <li {...props}>
                <Grid container alignItems="center">
                  <Grid item>
                    <Image
                      src={img_url}
                      alt="user_avatar"
                      width="30"
                      height="30"
                      className={styles.avatar}
                    />
                  </Grid>
                  <Typography variant="body1" color="text.secondary">
                    {name}
                  </Typography>
                </Grid>
              </li>
            );
          }}
        />
      </main>
    </div>
  );
};

export default Home;
